{
    'name': 'Gestion du Patrimoine',
    'version': '17.0',
    'category': 'Asset Management',
    'summary': 'Module de gestion du patrimoine géographique et actif',
    'description': 'Module de Gestion du Patrimoine',
    'author': 'IDIRISSI AROUSSI YOUNESS',
    'website': '',
    'depends': ['base'],
    'data': [
        'views/type_unite_views.xml',
        'views/unite_views.xml',
        'views/type_patrimoine_views.xml',
        'views/categorie_personnel_views.xml',
        'views/personnel_views.xml',
        'views/etat_views.xml',
        'views/famille_views.xml',
        'views/sous_famille_views.xml',
        'views/marque_views.xml',
        'views/categorie_patrimoine_actif_views.xml',
        'views/fournisseur_views.xml',
        'views/patrimoine_geographique_views.xml',
        'views/patrimoine_actif_views.xml',
        'views/etat_patrimoine_actif_views.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': True,
}
